// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {backend} from '../models';

export function Call_AddAccount(arg1:string,arg2:string,arg3:string,arg4:string,arg5:any,arg6:string,arg7:string,arg8:string,arg9:string):Promise<number>;

export function Call_ApplyUpdate():Promise<string>;

export function Call_ChangeMasterPassword(arg1:string,arg2:string):Promise<string>;

export function Call_CheckEmergencyConfig():Promise<boolean>;

export function Call_CheckUpdate():Promise<main.UpdateInfo>;

export function Call_CopyToClipboard(arg1:string):Promise<void>;

export function Call_Decrypt(arg1:Array<number>):Promise<string>;

export function Call_DeletePermanently(arg1:number):Promise<void>;

export function Call_DeleteSecureFile(arg1:number):Promise<void>;

export function Call_DownloadFile(arg1:number):Promise<Array<string>>;

export function Call_DownloadUpdate(arg1:string):Promise<string>;

export function Call_ExportAccounts(arg1:string):Promise<string>;

export function Call_GetAccountByID(arg1:number):Promise<backend.Account>;

export function Call_GetAccounts(arg1:string,arg2:any):Promise<Array<backend.Account>>;

export function Call_GetAllAccountsForDropdown():Promise<Array<backend.Account>>;

export function Call_GetAllChildren(arg1:number):Promise<Array<backend.Account>>;

export function Call_GetAllFiles():Promise<Array<backend.SecureFile>>;

export function Call_GetAppVersion():Promise<string>;

export function Call_GetLockoutStatus():Promise<Array<number>>;

export function Call_IsFirstRun():Promise<boolean>;

export function Call_LockSession():Promise<void>;

export function Call_RecoverWithCode(arg1:string,arg2:string):Promise<string>;

export function Call_RestoreAccount(arg1:number):Promise<void>;

export function Call_SaveFileToDisk(arg1:number):Promise<string>;

export function Call_SearchAccounts(arg1:string,arg2:string):Promise<Array<backend.Account>>;

export function Call_SetupMaster(arg1:string):Promise<string>;

export function Call_Unlock(arg1:string):Promise<boolean>;

export function Call_UpdateAccount(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string):Promise<void>;

export function Call_UpdateFile(arg1:number,arg2:any,arg3:string,arg4:string):Promise<void>;

export function Call_UpdateLastViewed(arg1:number):Promise<void>;

export function Call_UpdateStatus(arg1:number,arg2:string):Promise<void>;

export function Call_UploadFile(arg1:any,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;
