// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Call_AddAccount(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['Call_AddAccount'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function Call_ApplyUpdate() {
  return window['go']['main']['App']['Call_ApplyUpdate']();
}

export function Call_ChangeMasterPassword(arg1, arg2) {
  return window['go']['main']['App']['Call_ChangeMasterPassword'](arg1, arg2);
}

export function Call_CheckEmergencyConfig() {
  return window['go']['main']['App']['Call_CheckEmergencyConfig']();
}

export function Call_CheckUpdate() {
  return window['go']['main']['App']['Call_CheckUpdate']();
}

export function Call_CopyToClipboard(arg1) {
  return window['go']['main']['App']['Call_CopyToClipboard'](arg1);
}

export function Call_Decrypt(arg1) {
  return window['go']['main']['App']['Call_Decrypt'](arg1);
}

export function Call_DeletePermanently(arg1) {
  return window['go']['main']['App']['Call_DeletePermanently'](arg1);
}

export function Call_DeleteSecureFile(arg1) {
  return window['go']['main']['App']['Call_DeleteSecureFile'](arg1);
}

export function Call_DownloadFile(arg1) {
  return window['go']['main']['App']['Call_DownloadFile'](arg1);
}

export function Call_DownloadUpdate(arg1) {
  return window['go']['main']['App']['Call_DownloadUpdate'](arg1);
}

export function Call_ExportAccounts(arg1) {
  return window['go']['main']['App']['Call_ExportAccounts'](arg1);
}

export function Call_GetAccountByID(arg1) {
  return window['go']['main']['App']['Call_GetAccountByID'](arg1);
}

export function Call_GetAccounts(arg1, arg2) {
  return window['go']['main']['App']['Call_GetAccounts'](arg1, arg2);
}

export function Call_GetAllAccountsForDropdown() {
  return window['go']['main']['App']['Call_GetAllAccountsForDropdown']();
}

export function Call_GetAllChildren(arg1) {
  return window['go']['main']['App']['Call_GetAllChildren'](arg1);
}

export function Call_GetAllFiles() {
  return window['go']['main']['App']['Call_GetAllFiles']();
}

export function Call_GetLockoutStatus() {
  return window['go']['main']['App']['Call_GetLockoutStatus']();
}

export function Call_IsFirstRun() {
  return window['go']['main']['App']['Call_IsFirstRun']();
}

export function Call_LockSession() {
  return window['go']['main']['App']['Call_LockSession']();
}

export function Call_RecoverWithCode(arg1, arg2) {
  return window['go']['main']['App']['Call_RecoverWithCode'](arg1, arg2);
}

export function Call_RestoreAccount(arg1) {
  return window['go']['main']['App']['Call_RestoreAccount'](arg1);
}

export function Call_SaveFileToDisk(arg1) {
  return window['go']['main']['App']['Call_SaveFileToDisk'](arg1);
}

export function Call_SearchAccounts(arg1, arg2) {
  return window['go']['main']['App']['Call_SearchAccounts'](arg1, arg2);
}

export function Call_SetupMaster(arg1) {
  return window['go']['main']['App']['Call_SetupMaster'](arg1);
}

export function Call_Unlock(arg1) {
  return window['go']['main']['App']['Call_Unlock'](arg1);
}

export function Call_UpdateAccount(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['Call_UpdateAccount'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function Call_UpdateFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Call_UpdateFile'](arg1, arg2, arg3, arg4);
}

export function Call_UpdateLastViewed(arg1) {
  return window['go']['main']['App']['Call_UpdateLastViewed'](arg1);
}

export function Call_UpdateStatus(arg1, arg2) {
  return window['go']['main']['App']['Call_UpdateStatus'](arg1, arg2);
}

export function Call_UploadFile(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['Call_UploadFile'](arg1, arg2, arg3, arg4, arg5);
}
